export function get(element) {
    return document.getElementById(element);
}
export const $ = {
    root: get("root"),
    content: get("content"),
    mainpanel: get("mainpanel"),
    instructionpanel: get("instructionpanel"),
    warnings: get("warnings"),

    phishing: get("phishing"),
    phishingtext0: get("phishingtext0"),
    phishingtext1: get("phishingtext1"),
    phishingtext2: get("phishingtext2"),
    phishingcheck: get("phishingcheck"),
    cancelwarning: get("cancelwarning"),
    sameacctbutton: get("sameacctbutton"),
    nicknamebutton: get("nicknamebutton"),

    suffix: get("suffix"),
    suffixtext0: get("suffixtext0"),
    suffixtext1: get("suffixtext1"),
    suffixtext2: get("suffixtext2"),
    suffixacceptbutton: get("suffixacceptbutton"),
    suffixcancelbutton: get("suffixcancelbutton"),

    http: get("http"),
    httptext: get("httptext"),

    zero: get("zero"),
    zerotext: get("zerotext"),

    forget: get("forget"),
    forgettext: get("forgettext"),
    toforgetlist: get("toforgetlist"),
    forgetcancelbutton: get("forgetcancelbutton"),
    forgetbutton: get("forgetbutton"),

    changesitename: get("changesitename"),
    changesitenametext: get("changesitenametext"),
    changesitenameokbutton: get("changesitenameokbutton"),

    changeusername: get("changeusername"),
    changeusernametext: get("changeusernametext"),
    changeusernameokbutton: get("changeusernameokbutton"),

    changesuperpw: get("changesuperpw"),
    changesuperpwinfo: get("changesuperpwinfo"),
    changesuperpwdiv: get("changesuperpwdiv"),
    changesuperpwcancelbutton: get("changesuperpwcancelbutton"),
    // Change all account passwords, even provided ones
    changesuperpwlosebutton: get("changesuperpwlosebutton"),
    // Keep account passwords as if provided
    changesuperpwkeepoldinput: get("changesuperpwkeepoldinput"),
    changesuperpwkeepoldtypo: get("changesuperpwkeepoldtypo"),
    changesuperpwkeepbutton: get("changesuperpwkeepbutton"),

    nopw: get("nopw"),
    nopwtext: get("nopwtext"),

    multiple: get("multiple"),
    multipletext: get("multipletext"),

    helptext: get("helptext"),

    domainnamehelptext: get("domainnamehelptext"),
    domainnamehelptextclose: get("domainnamehelptextclose"),
    domainnamehelptextmore: get("domainnamehelptextmore"),

    superpwhelptext: get("superpwhelptext"),
    superpwhelptextclose: get("superpwhelptextclose"),
    superpwhelptextmore: get("superpwhelptextmore"),

    sitenamehelptext: get("sitenamehelptext"),
    sitenamehelptextclose: get("sitenamehelptextclose"),
    sitenamehelptextmore: get("sitenamehelptextmore"),

    usernamehelptext: get("usernamehelptext"),   
    sharedref: get("sharedref"),
    usernamehelptextclose: get("usernamehelptextclose"),
    usernamehelptextmore: get("usernamehelptextmore"),

    sitepwhelptext: get("sitepwhelptext"),
    sitepwhelptextclose: get("sitepwhelptextclose"),
    sitepwhelptextmore: get("sitepwhelptextmore"),

    sections: get("sections"),
    whoinfo: get("whoinfo"),
    whodiv: get("whodiv"),

    overviewinfo: get("overviewinfo"),
    overview: get("overview"),
    overviewdiv: get("overviewdiv"),

    basicinfo: get("basicinfo"),
    "using-the-extension": get("using-the-extension"),
    basicdiv: get("basicdiv"),

    domainnameinfo: get("domainnameinfo"),
    "the-domain-name": get("the-domain-name"),
    domainnamediv: get("domainnamediv"),

    superpwinfo: get("superpwinfo"),
    "your-super-password": get("your-super-password"),
    superpwdiv: get("superpwdiv"),

    sitenameinfo: get("sitenameinfo"),
    "your-site-nickname": get("your-site-nickname"),
    sitenamediv: get("sitenamediv"),
    changeref: get("changeref"),

    usernameinfo: get("usernameinfo"),
    "your-user-name": get("your-user-name"),
    usernamediv: get("usernamediv"),

    sitepwinfo: get("sitepwinfo"),
    "your-site-password": get("your-site-password"),
    sitepwdiv: get("sitepwdiv"),

    provideref: get("provideref"),
    provideinfo: get("provideinfo"),
    "providing-a-password": get("providing-a-password"),
    providediv: get("providediv"),

    menusinfo: get("menusinfo"),
    "input-field-menus": get("input-field-menus"),
    menusdiv: get("menusdiv"),

    settingsinfo: get("settingsinfo"),
    "additional-settings": get("additional-settings"),
    settingsdiv: get("settingsdiv"),

    acceptableref: get("acceptableref"),
    downloadref: get("downloadref"),
    exportref: get("exportref"),
    acceptableinfo: get("acceptableinfo"),
    "computing-an-acceptable-password": get("computing-an-acceptable-password"),
    acceptablediv: get("acceptablediv"),

    changeinfo: get("changeinfo"),
    "changing-an-account-password": get("changing-an-account-password"),
    changediv: get("changediv"),

    clipboardinfo: get("clipboardinfo"),
    "using-the-clipboard": get("using-the-clipboard"),
    clipboarddiv: get("clipboarddiv"),

    phishinginfo: get("phishinginfo"),
    "phishing-warning": get("phishing-warning"),
    phishingdiv: get("phishingdiv"),

    syncinfo: get("syncinfo"),
    "synchronizing-across-your-machines": get("synchronizing-across-your-machines"),
    syncdiv: get("syncdiv"),

    sharedcredsinfo: get("sharedcredsinfo"),
    "shared-credentials": get("shared-credentials"),
    sharedcredsdiv: get("sharedcredsdiv"),

    sharedinfo: get("sharedinfo"),
    "shared-machines": get("shared-machines"),
    shareddiv: get("shareddiv"),

    downloadinfo: get("downloadinfo"),
    "downloading-your-settings": get("downloading-your-settings"),
    downloaddiv: get("downloaddiv"),

    exportinfo: get("exportinfo"),
    "exporting-your-passwords": get("exporting-your-passwords"),
    exportdiv: get("exportdiv"),

    extensioninfo: get("extensioninfo"),
    "the-extension-and-the-web-page": get("the-extension-and-the-web-page"),
    extensiondiv: get("extensiondiv"),

    autofillinfo: get("autofillinfo"),
    "Browser Autofill": get("Browser Autofill"),
    autofilldiv: get("autofilldiv"),

    sourceinfo: get("sourceinfo"),
    "source-code": get("source-code"),
    sourcediv: get("sourcediv"),

    developersinfo: get("developersinfo"),
    "developers": get("developers"),
    developersdiv: get("developersdiv"),

    paymentinfo: get("paymentinfo"),
    "voluntary-payment": get("voluntary-payment"),
    paymentdiv: get("paymentdiv"),

    creditsinfo: get("creditsinfo"),
    creditsdiv: get("creditsdiv"),

    settingsmenu: get("settingsmenu"),
    providesitepwdiv: get("providesitepwdiv"),
    providesitepw: get("providesitepw"),
    providesitepwlabel: get("providesitepwlabel"),
    clearsuperpw: get("clearsuperpw"),
    hidesitepw: get("hidesitepw"),
    defaultsettings: get("defaultsettings"),
    pwlength: get("pwlength"),
    startwithletter: get("startwithletter"),
    allowlowercheckbox: get("allowlowercheckbox"),
    allowlower: get("allowlower"),
    requirelower: get("requirelower"),
    minlower: get("minlower"),
    allowuppercheckbox: get("allowuppercheckbox"),
    allowupper: get("allowupper"),
    requireupper: get("requireupper"),
    minupper: get("minupper"),
    allownumbercheckbox: get("allownumbercheckbox"),
    allownumber: get("allownumber"),
    requirenumber: get("requirenumber"),
    minnumber: get("minnumber"),
    allowspecialcheckbox: get("allowspecialcheckbox"),
    allowspecial: get("allowspecial"),
    requirespecial: get("requirespecial"),
    minspecial: get("minspecial"),
    specials: get("specials"),
    makedefaultbutton: get("makedefaultbutton"),
    sitedatagetbutton: get("sitedatagetbutton"),
    data: get("data"),
    exportbutton: get("exportbutton"),
    pwdata: get("pwdata"),
    main: get("main"),
    top: get("top"),
    logo: get("logo"),
    logopw: get("logopw"),
    title: get("title"),
    ssplogo: get("ssplogo"),
    domainname: get("domainname"),
    domainname3bluedots: get("domainname3bluedots"),
    domainnamemenu: get("domainnamemenu"),
    domainnamemenuforget: get("domainnamemenuforget"),
    domainnamemenuhelp: get("domainnamemenuhelp"),
    "superpw-strength-meter": get("superpw-strength-meter"),
    superpw: get("superpw"),
    superpw3bluedots: get("superpw3bluedots"),
    superpwmenu: get("superpwmenu"),
    superpwmenuaccount: get("superpwmenuaccount"),
    superpwmenushow: get("superpwmenushow"),
    superpwmenuhide: get("superpwmenuhide"),
    superpwmenuhelp: get("superpwmenuhelp"),
    sitenamerow: get("sitenamerow"),
    sitename: get("sitename"),
    sitename3bluedots: get("sitename3bluedots"),
    sitenamemenu: get("sitenamemenu"),
    sitenamemenuaccount: get("sitenamemenuaccount"),
    sitenamemenuforget: get("sitenamemenuforget"),
    sitenamemenuhelp: get("sitenamemenuhelp"),
    sitenames: get("sitenames"),
    usernamerow: get("usernamerow"),
    username: get("username"),
    usernamecopied: get("usernamecopied"),
    usernamenotcopied: get("usernamenotcopied"),
    username3bluedots: get("username3bluedots"),
    usernamemenu: get("usernamemenu"),
    usernamemenuforget: get("usernamemenuforget"),
    usernamemenucopy: get("usernamemenucopy"),
    usernamemenuhelp: get("usernamemenuhelp"),
    usernames: get("usernames"),
    "sitepw-strength-meter": get("sitepw-strength-meter"),
    sitepw: get("sitepw"),
    sitepwcopied: get("sitepwcopied"),
    sitepwnotcopied: get("sitepwnotcopied"),
    sitepw3bluedots: get("sitepw3bluedots"),
    sitepwmenu: get("sitepwmenu"),
    sitepwmenuaccount: get("sitepwmenuaccount"),
    sitepwmenushow: get("sitepwmenushow"),
    sitepwmenuhide: get("sitepwmenuhide"),
    sitepwmenucopy: get("sitepwmenucopy"),
    sitepwmenuhelp: get("sitepwmenuhelp"),
    bottom: get("bottom"),
    settingsshow: get("settingsshow"),
    settingssave: get("settingssave"),
    clearclipboard: get("clearclipboard"),
    maininfo: get("maininfo"),
    instructionopen: get("instructionopen"),
    instructionclose: get("instructionclose"),
};